"""Build the bundled Lucide icon archive and the `Icon` name enum.

Run after changing the pinned `lucide-static` version in the browser client:

    python -m leika._icons_generate_enum
    ruff format src/leika/_icons_enum.py src/leika/_icons_enum.pyi

The client chrome uses `lucide-react`; this packages the same icon set as
plain SVG so the Python API can send icon markup to the browser. Keep the two
on the same Lucide version.
"""

from __future__ import annotations

import zipfile
from pathlib import Path

HERE_DIR = Path(__file__).resolve().parent
ICON_DIR = HERE_DIR / "_icons"
ICON_ARCHIVE = ICON_DIR / "lucide-icons.zip"
SOURCE_DIR = HERE_DIR / "client" / "node_modules" / "lucide-static" / "icons"


def enum_name_from_icon(name: str) -> str:
    """Capitalize an icon name for use as an enum name."""
    name = name.upper()
    name = name.replace("-", "_")
    if name[0].isdigit():
        name = "ICON_" + name
    return name


def build_archive() -> list[str]:
    """Repack the installed Lucide SVGs and return the icon names."""
    if not SOURCE_DIR.is_dir():
        raise SystemExit(f"{SOURCE_DIR} not found; run `npm ci` in src/leika/client first.")
    # `lucide-static` also ships sprite/font variants; only the flat icon SVGs
    # are packaged.
    sources = sorted(path for path in SOURCE_DIR.glob("*.svg"))
    if not sources:
        raise SystemExit(f"no SVGs found in {SOURCE_DIR}")

    ICON_DIR.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(ICON_ARCHIVE, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sources:
            archive.writestr(path.name, path.read_text(encoding="utf-8"))
    return [path.stem for path in sources]


def write_enum(icon_names: list[str]) -> None:
    header_doc = [
        "# Automatically generated by `_icons_generate_enum.py`",
        "# Icons from Lucide (https://lucide.dev), ISC licensed.",
    ]
    class_doc = [
        '    """\'Enum\' class for referencing Lucide icons.',
        "",
        "    We don't subclass enum.Enum for performance reasons -- importing an enum with",
        "    thousands of names can result in import times in the hundreds of milliseconds.",
    ]

    # Stub file. This is used by type checkers.
    (HERE_DIR / "_icons_enum.pyi").write_text(
        "\n".join(
            header_doc
            + [
                "from typing import NewType",
                "",
                "IconName = NewType('IconName', str)",
                '"""Name of an icon. Should be generated via `leika.Icon.*`."""',
                "",
                "class Icon:",
            ]
            + class_doc
            + ['    """', ""]
            + [
                # Prefix names that start with a digit, which can't be Python
                # identifiers on their own.
                f"    {enum_name_from_icon(icon)}: IconName = IconName('{icon}')"
                for icon in icon_names
            ]
        )
    )

    # Source. This is used at runtime + by Sphinx for documentation.
    (HERE_DIR / "_icons_enum.py").write_text(
        "\n".join(
            header_doc
            + [
                "from typing import NewType",
                "",
                "IconName = NewType('IconName', str)",
                '"""Name of an icon. Should be generated via `leika.Icon.*`."""',
                "",
                "",
                "class _IconStringConverter(type):",
                "    def __getattr__(self, __name: str) -> IconName:",
                '        if not __name.startswith("_"):',
                '            return IconName(__name.lower().replace("_", "-"))',
                "        else:",
                "            raise AttributeError()",
                "",
                "",
                "class Icon(metaclass=_IconStringConverter):",
            ]
            + class_doc
            + [
                "",
                "    Attributes:",
            ]
            + [
                f"        {enum_name_from_icon(icon)} (IconName): The :code:`{icon}` icon."
                for icon in icon_names
            ]
            + ['    """']
        )
    )


if __name__ == "__main__":
    names = build_archive()
    write_enum(names)
    print(f"packaged {len(names)} Lucide icons into {ICON_ARCHIVE.name}")
