"""Named pages, each with an independent pane registry and saved layout."""

from __future__ import annotations

import threading
import uuid
from collections.abc import Iterator
from typing import TYPE_CHECKING, NewType, cast

from . import _messages
from ._panes import Panes, _PanesAggregate
from ._validation import validate_layout_id, validate_renderer_string

if TYPE_CHECKING:
    from ._server import Server


PageId = NewType("PageId", str)

_DEFAULT_PAGE_ID = "default"
_DEFAULT_PAGE_NAME = "Main"
_PAGE_MAX = 128


def _validate_page_name(value: object) -> str:
    name = cast(str, validate_renderer_string(value, "page name"))
    if not name:
        raise ValueError("page name must not be empty.")
    return name


def _normalize_legacy_page_label(value: object) -> str:
    """Translate the former optional visualization label to a page name."""

    if value is None or value == "":
        return _DEFAULT_PAGE_NAME
    return _validate_page_name(value)


class Page:
    """One named page and the panes whose layout its viewers arrange."""

    def __init__(self, owner: Pages, page_id: str, name: str, panes: Panes) -> None:
        self._owner = owner
        self._page_id = page_id
        self._name = name
        self.panes = panes
        """Pane API scoped to this page."""

    @property
    def page_id(self) -> PageId:
        """Stable identifier used to persist this page's browser layout."""

        return PageId(self._page_id)

    @property
    def name(self) -> str:
        """Unique name displayed in the page selector."""

        with self._owner._lock:
            return self._name

    @name.setter
    def name(self, value: str) -> None:
        self._owner._rename(self, _validate_page_name(value))


class Pages:
    """Declare the named pages in a Leika workspace.

    Every server starts with :attr:`default`. Use :meth:`add` for additional
    pages. Pane IDs are local to their page, while the server keeps the
    existing pane, Viser, payload, and raster limits aggregate across all
    pages.
    """

    def __init__(
        self,
        owner: Server,
        default_name: str = _DEFAULT_PAGE_NAME,
    ) -> None:
        self._owner = owner
        self._lock = threading.RLock()
        self._terminal = False
        self._page_from_page_id: dict[str, Page] = {}
        self._aggregate = _PanesAggregate(owner)
        self.default = self._add(
            _validate_page_name(default_name),
            _DEFAULT_PAGE_ID,
            is_default=True,
        )
        """The stable default page used by the one-page compatibility API."""

    def _make_panes(self, page_id: str) -> Panes:
        """Construct a page registry without publishing ahead of its page."""

        return Panes(
            self._owner,
            page_id=page_id,
            aggregate=self._aggregate,
            queue_snapshot=False,
        )

    def _check_name_available(self, name: str, *, excluding: Page | None = None) -> None:
        with self._lock:
            if any(
                page is not excluding and page._name == name
                for page in self._page_from_page_id.values()
            ):
                raise ValueError(f"Page name {name!r} already exists.")

    def _add(self, name: str, page_id: str, *, is_default: bool) -> Page:
        with self._lock:
            if self._terminal:
                raise RuntimeError("Pages is no longer active.")
            if page_id in self._page_from_page_id:
                raise ValueError(f"Page ID {page_id!r} already exists.")
            self._check_name_available(name)
            if len(self._page_from_page_id) >= _PAGE_MAX:
                raise RuntimeError(f"A workspace cannot own more than {_PAGE_MAX} pages.")

            panes = self._make_panes(page_id)
            page = Page(self, page_id, name, panes)
            try:
                self._owner._websock_server.queue_messages_or_raise(
                    (
                        _messages.PageCreateMessage(
                            page_id=page_id,
                            name=name,
                            is_default=is_default,
                        ),
                        panes._snapshot_message(),
                        _messages.PageCatalogMessage(
                            page_ids=tuple(self._page_from_page_id) + (page_id,)
                        ),
                    )
                )
            except BaseException:
                panes._retire_without_queue()
                raise
            self._page_from_page_id[page_id] = page
            return page

    def add(self, name: str, *, page_id: str | None = None) -> Page:
        """Add a page and return its page-scoped pane API.

        Args:
            name: Unique name displayed in the page selector.
            page_id: Stable layout identity. A UUID is generated by default;
                pass an explicit value to restore layouts across restarts.

        Returns:
            The new page.
        """

        name = _validate_page_name(name)
        resolved_page_id = (
            str(uuid.uuid4()) if page_id is None else validate_layout_id(page_id, "Page ID")
        )
        return self._add(name, resolved_page_id, is_default=False)

    def _rename(self, page: Page, name: str) -> None:
        with self._lock:
            if self._terminal:
                raise RuntimeError("Pages is no longer active.")
            if self._page_from_page_id.get(page._page_id) is not page:
                raise RuntimeError("Page is no longer active.")
            if page._name == name:
                return
            self._check_name_available(name, excluding=page)
            self._owner._websock_server.queue_message_or_raise(
                _messages.PageUpdateMessage(page_id=page._page_id, name=name)
            )
            page._name = name

    def _retire_without_queue(self) -> None:
        with self._lock:
            if self._terminal:
                return
            self._terminal = True
            pages = tuple(self._page_from_page_id.values())
        for page in pages:
            page.panes._retire_without_queue()

    def __len__(self) -> int:
        with self._lock:
            return len(self._page_from_page_id)

    def __iter__(self) -> Iterator[Page]:
        with self._lock:
            return iter(tuple(self._page_from_page_id.values()))
