"""Synchronize generated browser protocol and version files with Python."""

from __future__ import annotations

import argparse
import os
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

import leika
import leika._client_autobuild as client_autobuild
import leika.infra
from leika._messages import Message

ROOT = Path(__file__).resolve().parent
CLIENT_DIR = ROOT / "src/leika/client"
MESSAGES_PATH = ROOT / "src/leika/client/src/WebsocketMessages.ts"
VERSION_PATH = ROOT / "src/leika/client/src/VersionInfo.ts"
PRETTIER_PATH = (
    CLIENT_DIR / "node_modules/.bin" / ("prettier.cmd" if sys.platform == "win32" else "prettier")
)


def _version_source() -> str:
    return (
        "// Generated by sync_client_server.py; do not edit manually.\n"
        f'export const LEIKA_VERSION = "{leika.__version__}";\n'
    )


def _messages_source() -> str:
    return (
        leika.infra.generate_typescript_interfaces(Message) + "\n"
        "/** Hash of the message schema this bundle was built against. Sent with\n"
        " * the version at connect, so a server running different code is turned\n"
        " * away with a reason instead of feeding the page fields it cannot read. */\n"
        f'export const LEIKA_PROTOCOL = "{leika.infra.protocol_fingerprint(Message)}";\n'
    )


def _fsync_directory(directory: Path) -> None:
    """Persist a replaced directory entry on platforms that support it."""
    if os.name == "nt":
        return
    descriptor = os.open(directory, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    if check:
        try:
            valid_target = not path.is_symlink() and path.is_file()
            current = valid_target and path.read_text(encoding="utf-8") == content
        except OSError:
            current = False
        if not current:
            print(f"out of date: {path.relative_to(ROOT)}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise RuntimeError(f"refusing to replace generated-file symlink: {path}")
    if path.exists():
        metadata = path.stat()
        if not stat.S_ISREG(metadata.st_mode):
            raise RuntimeError(f"generated-file target is not regular: {path}")
        mode = stat.S_IMODE(metadata.st_mode)
    else:
        mode = 0o644
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            os.chmod(temporary, mode)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        _fsync_directory(path.parent)
    finally:
        if temporary.exists():
            temporary.unlink()
    print(f"updated: {path.relative_to(ROOT)}")
    return True


def _prettier_runtime() -> tuple[Path, dict[str, str]]:
    """Resolve the lockfile-installed Prettier and pinned Node runtime."""
    bin_dir, virtual_env = client_autobuild._resolve_node()
    if not PRETTIER_PATH.is_file():
        raise RuntimeError(
            "Prettier is not installed from package-lock.json; run "
            "`npm ci` in src/leika/client before synchronizing generated files"
        )
    return PRETTIER_PATH, client_autobuild._node_env(bin_dir, virtual_env)


def _format_source(
    path: Path,
    content: str,
    *,
    prettier: Path,
    env: dict[str, str],
) -> str:
    """Format generated TypeScript exactly as the checked-in client does."""
    result = subprocess.run(
        [str(prettier), "--stdin-filepath", str(path)],
        cwd=CLIENT_DIR,
        env=env,
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--messages", action="store_true", help="synchronize message types")
    parser.add_argument("--version", action="store_true", help="synchronize package version")
    parser.add_argument("--check", action="store_true", help="check without writing")
    args = parser.parse_args()
    if not args.messages and not args.version:
        args.messages = args.version = True

    outputs: list[tuple[Path, str]] = []
    if args.messages:
        outputs.append((MESSAGES_PATH, _messages_source()))
    if args.version:
        outputs.append((VERSION_PATH, _version_source()))

    try:
        # npm ci replaces node_modules and nodeenv creation replaces its bin
        # directory. Keep the client-build lock through formatting and every
        # generated-file check/replacement. Per-file publication is atomic,
        # and no build can observe the brief interval between the protocol and
        # version replacements.
        with client_autobuild._build_lock():
            prettier, env = _prettier_runtime()
            outputs = [
                (path, _format_source(path, content, prettier=prettier, env=env))
                for path, content in outputs
            ]
            current = True
            for path, content in outputs:
                current = _write_or_check(path, content, check=args.check) and current
    except (FileNotFoundError, RuntimeError) as exc:
        print(f"cannot run the pinned Prettier toolchain: {exc}")
        return 1
    except subprocess.CalledProcessError as exc:
        print(exc.stderr, end="")
        return exc.returncode

    return 0 if current else 1


if __name__ == "__main__":
    raise SystemExit(main())
