"""Synchronize generated browser protocol and version files with Python."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path

import leika
import leika.infra
from leika._messages import Message

ROOT = Path(__file__).resolve().parent
MESSAGES_PATH = ROOT / "src/leika/client/src/WebsocketMessages.ts"
VERSION_PATH = ROOT / "src/leika/client/src/VersionInfo.ts"


def _version_source() -> str:
    return (
        "// Generated by sync_client_server.py; do not edit manually.\n"
        f'export const LEIKA_VERSION = "{leika.__version__}";\n'
    )


def _write_or_check(path: Path, content: str, *, check: bool) -> bool:
    if check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            print(f"out of date: {path.relative_to(ROOT)}")
            return False
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"updated: {path.relative_to(ROOT)}")
    return True


def _format_source(path: Path, content: str) -> str:
    """Format generated TypeScript exactly as the checked-in client does."""
    result = subprocess.run(
        ["npx", "prettier", "--stdin-filepath", str(path)],
        cwd=ROOT / "src/leika/client",
        input=content,
        text=True,
        capture_output=True,
        check=True,
    )
    return result.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--messages", action="store_true", help="synchronize message types")
    parser.add_argument("--version", action="store_true", help="synchronize package version")
    parser.add_argument("--check", action="store_true", help="check without writing")
    args = parser.parse_args()
    if not args.messages and not args.version:
        args.messages = args.version = True

    outputs: list[tuple[Path, str]] = []
    if args.messages:
        outputs.append(
            (
                MESSAGES_PATH,
                leika.infra.generate_typescript_interfaces(Message),
            )
        )
    if args.version:
        outputs.append((VERSION_PATH, _version_source()))

    if args.check:
        try:
            outputs = [(path, _format_source(path, content)) for path, content in outputs]
        except FileNotFoundError:
            print("npx not found; cannot verify formatted generated files")
            return 1
        except subprocess.CalledProcessError as exc:
            print(exc.stderr, end="")
            return exc.returncode

    current = True
    for path, content in outputs:
        current = _write_or_check(path, content, check=args.check) and current
    if args.check:
        return 0 if current else 1

    try:
        subprocess.run(
            ["npx", "prettier", "-w", *(str(path) for path, _ in outputs)],
            cwd=ROOT / "src/leika/client",
            check=True,
        )
    except FileNotFoundError:
        print("npx not found; generated files were not formatted")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
