// Generated by sync_client_server.py; do not edit manually.
export const LEIKA_VERSION = "0.2.0";

/** Hash of the message schema this bundle was built against. Sent with
 * the version at connect, so a server running different code is turned
 * away with a reason instead of feeding the page fields it cannot read. */
export const LEIKA_PROTOCOL = "a6b221645c2b";
