// The "floating" control-panel layout, on the docking library.
//
// Mounts a DockManager over the canvas area and seeds it with ONE panel: the
// control panel, as an unmergeable floating window in the top-right corner.
// It supports drag, docking to either edge with a canvas inset, resizing from
// both edges, and click-the-handle to minimize. Because it's an ordinary dock
// panel, it also composes with any other panels later added to the surface
// (e.g. GUI tabs dragged out of a nested dockable area).

import React from "react";
import { ViewerContext, ViewerContextContents } from "../ViewerContext";
import { DockMetricsContext, useDock } from "../dock/DockContext";
import { DockManager } from "../dock/DockManager";
import * as ops from "../dock/layoutOps";
import { PanelRegistry, emptyLayout } from "../dock/types";
import { ControlPanelContents, PanelHeader } from "./ControlPanel";
import { useShowGenerated } from "./useShowGenerated";
import GeneratedGuiContainer from "./Generated";
import { GuiDockContext } from "./GuiDockContext";
import { SettingsButton } from "./SettingsPane";
import { useSettingsPanelOpen } from "./SettingsPanelController";
import { CONTROL_WIDTH_PX } from "./controlWidth";

// Memoized so a torn-out tab's whole GUI tree doesn't re-render every time
// unrelated dock state changes (it only depends on its container uuid).
const MemoizedGeneratedGuiContainer = React.memo(GeneratedGuiContainer);

/** The control panel's panel id, fixed so sync code can find it. Its group /
 * window ids are generated by the layout ops; sync code locates them via
 * findPanelGroup + findGroupLocation. */
const CONTROL_PANEL_ID = "leika-control-panel";

/** `data-testid` the e2e suite uses to find the control panel among the dock's
 * otherwise-generic panel elements. The dock derives `-handle` and
 * `-resize-left` / `-resize-right` from it. */
const CONTROL_PANEL_TESTID = "control-panel";

// Boundary pad between the panel and the container edge on first placement.
const PANEL_PAD_PX = 15;

/** Where the control panel currently sits, reported up to App so the
 * notifications layer can offset itself clear of a left-docked panel. */
export interface ControlDockState {
  side: "left" | "right" | null;
  widthPx: number;
  expanded: boolean;
}

export function ControlPanelDockSurface({
  children,
  onDockStateChange,
}: {
  /** Center content (the canvas layers), inset when the panel is docked. */
  children: React.ReactNode;
  onDockStateChange?: (state: ControlDockState) => void;
}) {
  const viewer = React.useContext(ViewerContext)!;

  // GUI tab groups rendered inside the dock surface register here (via
  // GuiDockContext); the registry hook owns the lifetime of their tabs' panel
  // specs.
  const { guiPanels, registerTabGroup } = useGuiTabPanelRegistry(viewer);
  const guiDockValue = React.useMemo(
    () => ({ registerTabGroup }),
    [registerTabGroup],
  );

  // The body keeps itself mounted at zero height when there is no GUI, so the
  // frame has to be told; otherwise its header/body gap hangs below a lone
  // "Connecting..." header.
  const showGenerated = useShowGenerated();
  const settingsOpen = useSettingsPanelOpen();
  const hasBody = showGenerated || settingsOpen;
  const controlPanelSpec: PanelRegistry = React.useMemo(
    () => ({
      [CONTROL_PANEL_ID]: {
        id: CONTROL_PANEL_ID,
        title: "Control panel",
        unmergeable: true,
        testId: CONTROL_PANEL_TESTID,
        titleNode: <PanelHeader actions={<SettingsButton />} />,
        render: () => <ControlPanelContents />,
        bodyIsEmpty: !hasBody,
      },
    }),
    [hasBody],
  );
  const panels: PanelRegistry = React.useMemo(
    () => ({ ...guiPanels, ...controlPanelSpec }),
    [guiPanels, controlPanelSpec],
  );

  // The DockManager mounts IMMEDIATELY around the canvas (an empty layout is
  // just a passthrough container) -- mounting it later would reparent the
  // children and remount active pane renderers. The
  // control panel window is then placed by ControlPanelDockSync once the
  // container width is measurable (top-right anchored).
  const initialLayout = React.useMemo(() => emptyLayout(), []);

  return (
    <GuiDockContext.Provider value={guiDockValue}>
      <DockManager initialLayout={initialLayout} panels={panels}>
        {children}
        <ControlPanelDockSync onDockStateChange={onDockStateChange} />
      </DockManager>
    </GuiDockContext.Provider>
  );
}

/** Owns the panel specs for GUI tab groups rendered inside the dock surface.
 * Each registered tab group gets a config-store subscription that keeps its
 * tabs' specs fresh (labels, icons, membership); when the SERVER removes the
 * tab group, its specs are dropped -- the DockManager's registry
 * reconciliation then removes the panels from wherever the user moved them.
 * Spec lifetime deliberately does NOT follow component mount state: a nested
 * tab group unmounts whenever an ancestor tab goes inactive, which must not
 * tear down its panels. */
function useGuiTabPanelRegistry(viewer: ViewerContextContents): {
  guiPanels: PanelRegistry;
  registerTabGroup: (uuid: string) => void;
} {
  const [guiPanels, setGuiPanels] = React.useState<PanelRegistry>({});
  // Per tab group: its config subscription, the panel ids it owns, and a
  // signature of the last-applied tab content (ids/labels/icons).
  const registry = React.useRef(
    new Map<
      string,
      { unsubscribe: () => void; panelIds: string[]; sig: string }
    >(),
  );

  const refreshTabGroup = React.useCallback(
    (uuid: string) => {
      const entry = registry.current.get(uuid);
      if (entry === undefined) return;
      const conf = viewer.useGuiConfig.get(uuid);
      const tabConf =
        conf !== undefined && conf.type === "GuiTabGroupMessage" ? conf : null;
      // The config store fires for ANY prop change on this uuid; only rebuild
      // the specs (new objects + icon elements, which re-renders every tab
      // panel) when the tab CONTENT actually changed.
      const sig =
        tabConf === null
          ? ""
          : JSON.stringify([
              tabConf.props._tab_container_ids,
              tabConf.props._tab_labels,
              tabConf.props._tab_icons_html,
            ]);
      if (tabConf !== null && sig === entry.sig) return;
      entry.sig = sig;
      const ownedBefore = new Set(entry.panelIds);
      if (tabConf === null) {
        entry.unsubscribe();
        registry.current.delete(uuid);
      } else {
        entry.panelIds = [...tabConf.props._tab_container_ids];
      }
      setGuiPanels((prev) => {
        const next: PanelRegistry = {};
        for (const [pid, spec] of Object.entries(prev)) {
          if (!ownedBefore.has(pid)) next[pid] = spec;
        }
        if (tabConf === null) return next;
        tabConf.props._tab_container_ids.forEach((cid: string, i: number) => {
          const iconHtml = tabConf.props._tab_icons_html[i];
          next[cid] = {
            id: cid,
            title: tabConf.props._tab_labels[i] ?? "Tab",
            icon:
              iconHtml == null ? undefined : (
                <div
                  className="relative size-3.5 [&_svg]:absolute [&_svg]:top-1/2 [&_svg]:w-3.5 [&_svg]:-translate-y-1/2"
                  dangerouslySetInnerHTML={{ __html: iconHtml }}
                />
              ),
            render: () => <MemoizedGeneratedGuiContainer containerUuid={cid} />,
          };
        });
        return next;
      });
    },
    [viewer],
  );
  const registerTabGroup = React.useCallback(
    (uuid: string) => {
      if (registry.current.has(uuid)) return;
      registry.current.set(uuid, {
        unsubscribe: viewer.useGuiConfig.subscribe(uuid, () =>
          refreshTabGroup(uuid),
        ),
        panelIds: [],
        // Sentinel that never matches a real signature, so the first refresh
        // always applies.
        sig: "\0unset",
      });
      refreshTabGroup(uuid);
    },
    [viewer, refreshTabGroup],
  );
  React.useEffect(() => {
    const reg = registry.current;
    return () => reg.forEach((entry) => entry.unsubscribe());
  }, []);
  return { guiPanels, registerTabGroup };
}

/** Non-rendering sync node inside the DockManager:
 * - places the floating window on mount;
 * - reports the panel's dock side/width/minimized state up to App (for the
 *   notifications offset).
 *
 * Test ids are NOT applied here: the panel spec declares `testId` and the dock
 * library renders it (plus `-handle` / `-resize-*`) itself. */
function ControlPanelDockSync({
  onDockStateChange,
}: {
  onDockStateChange?: (state: ControlDockState) => void;
}) {
  const dock = useDock();
  const metrics = React.useContext(DockMetricsContext);
  // Anchor for measuring the dock container: this component renders nothing
  // visible, so it keeps a hidden node to walk up from.
  const markerRef = React.useRef<HTMLSpanElement>(null);

  // Narrow containers (small browser windows, split screens): shrink the
  // panel to fit with its padding rather than spilling past the right edge.
  const fitToContainer = React.useCallback((width: number) => {
    const containerW =
      markerRef.current?.closest("[data-dock-root]")?.getBoundingClientRect()
        .width ?? 1280;
    return {
      containerW,
      width: Math.max(160, Math.min(width, containerW - 2 * PANEL_PAD_PX)),
    };
  }, []);

  // Initial placement: top-right corner.
  // Runs once on mount (addFloatingPanel no-ops if the panel is already
  // placed, so a StrictMode double-run is harmless).
  React.useLayoutEffect(() => {
    const { containerW, width } = fitToContainer(CONTROL_WIDTH_PX);
    dock.api.apply(
      (layout) =>
        ops.addFloatingPanel(
          layout,
          CONTROL_PANEL_ID,
          Math.max(PANEL_PAD_PX, containerW - width - PANEL_PAD_PX),
          PANEL_PAD_PX,
          width,
        ).layout,
    );
    // Initial placement only; the panel width is a constant, and the user is
    // free to resize the window afterwards.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Where is the control panel now?
  const controlGroupId = ops.findPanelGroup(dock.layout, CONTROL_PANEL_ID);
  const location =
    controlGroupId === null
      ? null
      : ops.findGroupLocation(dock.layout, controlGroupId);
  const side: "left" | "right" | "none" =
    location?.kind === "docked" ? location.edge : "none";
  const expanded =
    controlGroupId === null || dock.groups[controlGroupId]?.collapsed !== true;
  // RENDERED width (expanded px + strip/divider chrome): the notifications
  // offset must clear everything the region actually draws, not just the
  // expanded columns' model width.
  const dockedWidth =
    location?.kind === "docked"
      ? metrics.reservedWidth[location.edge]
      : CONTROL_WIDTH_PX;

  // Report dock state up to App (notifications offset).
  React.useEffect(() => {
    onDockStateChange?.({
      side: side === "none" ? null : side,
      widthPx: dockedWidth,
      expanded,
    });
  }, [side, dockedWidth, expanded, onDockStateChange]);

  return <span ref={markerRef} style={{ display: "none" }} />;
}
