// The desktop control panel, on the docking library.
//
// Mounts a DockManager over the canvas area and seeds it with ONE panel: the
// control panel, placed where the theme asks -- a floating window in the
// top-right corner, or docked to an edge. That is a starting position only:
// the panel is an ordinary dock panel, so the viewer can drag it, dock it to
// either edge with a canvas inset, resize it from both edges, and
// click-the-handle to minimize -- and it composes with any other panels later
// added to the surface (e.g. GUI tabs dragged out of a nested dockable area).
// The one chrome not drawn here is the phone's bottom sheet (ControlPanel).

import React from "react";
import { ViewerContext, ViewerContextContents } from "../ViewerContext";
import { DockMetricsContext, useDock } from "../dock/DockContext";
import { DockManager } from "../dock/DockManager";
import * as ops from "../dock/layoutOps";
import { DockLayout, PanelRegistry, emptyLayout } from "../dock/types";
import { ThemeConfigurationMessage } from "../WebsocketMessages";
import { ControlPanelContents, PanelHeader } from "./ControlPanel";
import { useShowGenerated } from "./useShowGenerated";
import GeneratedGuiContainer from "./Generated";
import { GuiDockContext } from "./GuiDockContext";
import { SettingsButton } from "./SettingsPane";
import { controlsSection, useControlsShown } from "./SettingsPanelController";
import { CONTROL_WIDTH_PX } from "./controlWidth";

// Memoized so a torn-out tab's whole GUI tree doesn't re-render every time
// unrelated dock state changes (it only depends on its container uuid).
const MemoizedGeneratedGuiContainer = React.memo(GeneratedGuiContainer);

/** The control panel's panel id, fixed so sync code can find it. Its group /
 * window ids are generated by the layout ops; sync code locates them via
 * findPanelGroup + findGroupLocation. */
const CONTROL_PANEL_ID = "leika-control-panel";

/** `data-testid` the e2e suite uses to find the control panel among the dock's
 * otherwise-generic panel elements. The dock derives `-handle` and
 * `-resize-left` / `-resize-right` from it. */
const CONTROL_PANEL_TESTID = "control-panel";

// Boundary pad between the panel and the container edge on first placement.
const PANEL_PAD_PX = 15;

/** The dock's `api.apply`, as specs built outside the DockManager see it. */
type ApplyLayout = (transform: (layout: DockLayout) => DockLayout) => void;

/** Where the control panel currently sits, reported up to App so the
 * notifications layer can offset itself clear of a left-docked panel. */
export interface ControlDockState {
  side: "left" | "right" | null;
  widthPx: number;
  expanded: boolean;
}

export function ControlPanelDockSurface({
  children,
  controlLayout,
  onDockStateChange,
}: {
  /** Center content (the canvas layers), inset when the panel is docked. */
  children: React.ReactNode;
  /** Where the server asked the panel to start (theme `control_layout`). */
  controlLayout: ThemeConfigurationMessage["control_layout"];
  onDockStateChange?: (state: ControlDockState) => void;
}) {
  const viewer = React.useContext(ViewerContext)!;

  // GUI tab groups rendered inside the dock surface register here (via
  // GuiDockContext); the registry hook owns the lifetime of their tabs' panel
  // specs. Like the control panel's reset, their specs are built OUTSIDE the
  // DockManager and reach its layout through a ref the sync node fills.
  const applyLayoutRef = React.useRef<ApplyLayout | null>(null);
  const { guiPanels, registerTabGroup } = useGuiTabPanelRegistry(
    viewer,
    applyLayoutRef,
  );
  const guiDockValue = React.useMemo(
    () => ({ registerTabGroup }),
    [registerTabGroup],
  );

  // The body keeps itself mounted at zero height when there is no GUI, so the
  // frame has to be told; otherwise its header/body gap hangs below a lone
  // "Connecting..." header.
  const hasGenerated = useShowGenerated();
  const controlsShown = useControlsShown();
  const hasBody = hasGenerated && controlsShown;
  // Double-clicking the handle sends the panel home; the sync node inside the
  // DockManager is what knows where that is, so the spec calls through a ref.
  const resetLayoutRef = React.useRef<() => void>(() => {});
  const controlPanelSpec: PanelRegistry = React.useMemo(
    () => ({
      [CONTROL_PANEL_ID]: {
        id: CONTROL_PANEL_ID,
        title: "Control panel",
        unmergeable: true,
        testId: CONTROL_PANEL_TESTID,
        titleNode: <PanelHeader actions={<SettingsButton />} />,
        render: () => <ControlPanelContents />,
        bodyIsEmpty: !hasBody,
        onResetLayout: () => resetLayoutRef.current(),
        // The handle toggles the generated controls. The sync node below maps
        // that state onto the dock group's collapsed state.
        onHandleClick: () => {
          controlsSection.toggle();
          return true;
        },
        // Expansion requests (a drop that lands the panel somewhere new) go
        // the same way: open the section, and the sync node's mirror unfolds
        // the group. Clearing the group flag directly would be re-folded.
        onExpand: () => {
          controlsSection.open();
          return true;
        },
        // Folded away, this panel is a 320px bar of empty card sitting over the
        // visualization. Let it go, and leave the connection badge behind as
        // the thing to hover to get it back.
        peekWhenCollapsed: true,
      },
    }),
    [hasBody],
  );
  const panels: PanelRegistry = React.useMemo(
    () => ({ ...guiPanels, ...controlPanelSpec }),
    [guiPanels, controlPanelSpec],
  );

  // The DockManager mounts IMMEDIATELY around the canvas (an empty layout is
  // just a passthrough container) -- mounting it later would reparent the
  // children and remount active pane renderers. The
  // control panel window is then placed by ControlPanelDockSync once the
  // container width is measurable (top-right anchored).
  const initialLayout = React.useMemo(() => emptyLayout(), []);

  return (
    <GuiDockContext.Provider value={guiDockValue}>
      <DockManager initialLayout={initialLayout} panels={panels}>
        {children}
        <ControlPanelDockSync
          controlLayout={controlLayout}
          onDockStateChange={onDockStateChange}
          resetLayoutRef={resetLayoutRef}
          applyLayoutRef={applyLayoutRef}
        />
      </DockManager>
    </GuiDockContext.Provider>
  );
}

/** Owns the panel specs for GUI tab groups rendered inside the dock surface.
 * Each registered tab group gets a config-store subscription that keeps its
 * tabs' specs fresh (labels, icons, membership); when the SERVER removes the
 * tab group, its specs are dropped -- the DockManager's registry
 * reconciliation then removes the panels from wherever the user moved them.
 * Spec lifetime deliberately does NOT follow component mount state: a nested
 * tab group unmounts whenever an ancestor tab goes inactive, which must not
 * tear down its panels. */
function useGuiTabPanelRegistry(
  viewer: ViewerContextContents,
  applyRef: React.MutableRefObject<ApplyLayout | null>,
): {
  guiPanels: PanelRegistry;
  registerTabGroup: (uuid: string) => void;
} {
  const [guiPanels, setGuiPanels] = React.useState<PanelRegistry>({});
  // Per tab group: its config subscription, the panel ids it owns, and a
  // signature of the last-applied tab content (ids/labels/icons).
  const registry = React.useRef(
    new Map<
      string,
      { unsubscribe: () => void; panelIds: string[]; sig: string }
    >(),
  );

  const refreshTabGroup = React.useCallback(
    (uuid: string) => {
      const entry = registry.current.get(uuid);
      if (entry === undefined) return;
      const conf = viewer.useGuiConfig.get(uuid);
      const tabConf =
        conf !== undefined && conf.type === "GuiTabGroupMessage" ? conf : null;
      // The config store fires for ANY prop change on this uuid; only rebuild
      // the specs (new objects + icon elements, which re-renders every tab
      // panel) when the tab CONTENT actually changed.
      const sig = tabConf === null ? "" : JSON.stringify(tabConf.props._tabs);
      if (tabConf !== null && sig === entry.sig) return;
      entry.sig = sig;
      const ownedBefore = new Set(entry.panelIds);
      if (tabConf === null) {
        entry.unsubscribe();
        registry.current.delete(uuid);
      } else {
        entry.panelIds = tabConf.props._tabs.map((tab) => tab.container_id);
      }
      setGuiPanels((prev) => {
        const next: PanelRegistry = {};
        for (const [pid, spec] of Object.entries(prev)) {
          if (!ownedBefore.has(pid)) next[pid] = spec;
        }
        if (tabConf === null) return next;
        tabConf.props._tabs.forEach((tab, index) => {
          const cid = tab.container_id;
          const iconHtml = tab.icon_html;
          next[cid] = {
            id: cid,
            title: tab.label,
            icon:
              iconHtml == null ? undefined : (
                <div
                  className="relative size-3.5 [&_svg]:absolute [&_svg]:top-1/2 [&_svg]:w-3.5 [&_svg]:-translate-y-1/2"
                  dangerouslySetInnerHTML={{ __html: iconHtml }}
                />
              ),
            render: () => <MemoizedGeneratedGuiContainer containerUuid={cid} />,
            // Home is the tab group the panel came from, at its declared
            // place among whichever tabs are still there. Reached the way
            // every panel's home is: a double-click on its title.
            onResetLayout: () => {
              applyRef.current?.((layout) => {
                const groupId = ops.findPanelGroup(layout, cid);
                const location =
                  groupId === null
                    ? null
                    : ops.findGroupLocation(layout, groupId);
                if (location?.kind === "area") return layout;
                return ops.addPanelToArea(
                  ops.removePanel(layout, cid),
                  `gui-tabs-${uuid}`,
                  cid,
                  index,
                );
              });
            },
          };
        });
        return next;
      });
    },
    [viewer],
  );
  const registerTabGroup = React.useCallback(
    (uuid: string) => {
      if (registry.current.has(uuid)) return;
      registry.current.set(uuid, {
        unsubscribe: viewer.useGuiConfig.subscribe(uuid, () =>
          refreshTabGroup(uuid),
        ),
        panelIds: [],
        // Sentinel that never matches a real signature, so the first refresh
        // always applies.
        sig: "\0unset",
      });
      refreshTabGroup(uuid);
    },
    [viewer, refreshTabGroup],
  );
  React.useEffect(() => {
    const reg = registry.current;
    return () => reg.forEach((entry) => entry.unsubscribe());
  }, []);
  return { guiPanels, registerTabGroup };
}

/** Non-rendering sync node inside the DockManager:
 * - places the floating window on mount;
 * - reports the panel's dock side/width/minimized state up to App (for the
 *   notifications offset).
 *
 * Test ids are NOT applied here: the panel spec declares `testId` and the dock
 * library renders it (plus `-handle` / `-resize-*`) itself. */
function ControlPanelDockSync({
  controlLayout,
  onDockStateChange,
  resetLayoutRef,
  applyLayoutRef,
}: {
  controlLayout: ThemeConfigurationMessage["control_layout"];
  onDockStateChange?: (state: ControlDockState) => void;
  /** Filled in here and called from the panel spec, which is built OUTSIDE the
   * DockManager and so cannot reach `useDock` itself. */
  resetLayoutRef: React.MutableRefObject<() => void>;
  /** Same arrangement for the GUI tab panels' own resets. */
  applyLayoutRef: React.MutableRefObject<ApplyLayout | null>;
}) {
  const dock = useDock();
  React.useEffect(() => {
    applyLayoutRef.current = dock.api.apply;
    return () => {
      applyLayoutRef.current = null;
    };
  }, [dock.api, applyLayoutRef]);
  const metrics = React.useContext(DockMetricsContext);
  // Anchor for measuring the dock container: this component renders nothing
  // visible, so it keeps a hidden node to walk up from.
  const markerRef = React.useRef<HTMLSpanElement>(null);

  // Narrow containers (small browser windows, split screens): shrink the
  // panel to fit with its padding rather than spilling past the right edge.
  const fitToContainer = React.useCallback((width: number) => {
    const containerW =
      markerRef.current?.closest("[data-dock-root]")?.getBoundingClientRect()
        .width ?? 1280;
    return {
      containerW,
      width: Math.max(160, Math.min(width, containerW - 2 * PANEL_PAD_PX)),
    };
  }, []);

  /** The panel's home: top-right corner, at the panel's one width. */
  const defaultRect = React.useCallback(() => {
    const { containerW, width } = fitToContainer(CONTROL_WIDTH_PX);
    return {
      x: Math.max(PANEL_PAD_PX, containerW - width - PANEL_PAD_PX),
      y: PANEL_PAD_PX,
      width,
    };
  }, [fitToContainer]);

  // Placement: put the panel where the theme asks, and only when the theme
  // ASKS. The dock mounts before the server's theme message can arrive, so
  // placement has to be reactive rather than one-shot -- but it must react to
  // the VALUE, not the message: the theme is replayed on every reconnect, and
  // a replayed "left" must not stomp a layout the viewer has since rearranged.
  // The primitive selector upstream gives exactly that -- this effect fires on
  // mount and on genuine changes, nothing else. (The flip side, noted for
  // whoever needs it: calling configure_theme again with the UNCHANGED value
  // cannot force a re-place for connected viewers.)
  //
  // Every branch is guarded so a re-run against a layout that already
  // satisfies it changes nothing: addFloatingPanel no-ops when placed, the
  // docked branch returns early when already on the target edge (a bare
  // dockToEdge would detach and re-dock, churning a user's region
  // arrangement), and the floating branch only moves a panel that is NOT
  // already floating (so it can never teleport a window the viewer has moved).
  React.useLayoutEffect(() => {
    dock.api.apply((layout) => {
      let next = layout;
      let groupId = ops.findPanelGroup(next, CONTROL_PANEL_ID);
      if (groupId === null) {
        const { x, y, width } = defaultRect();
        next = ops.addFloatingPanel(next, CONTROL_PANEL_ID, x, y, width).layout;
        groupId = ops.findPanelGroup(next, CONTROL_PANEL_ID);
        if (groupId === null) return next;
      }
      const location = ops.findGroupLocation(next, groupId);
      if (controlLayout === "left" || controlLayout === "right") {
        if (location?.kind === "docked" && location.edge === controlLayout) {
          return next;
        }
        // No width to set: a fresh region opens at DEFAULT_REGION_PX, which
        // IS the panel's width -- and a region the viewer already has on this
        // edge keeps whatever width they gave it.
        return ops.dockToEdge(next, [groupId], controlLayout);
      }
      if (location !== null && location.kind !== "floating") {
        const { x, y, width } = defaultRect();
        return ops.floatGroup(next, groupId, x, y, width).layout;
      }
      return next;
    });
    // defaultRect and dock.api are stable; the placement follows the theme.
  }, [controlLayout]);

  // Keep the dock group aligned with the generated controls' visibility.
  const bodyVisible = useControlsShown();
  React.useEffect(() => {
    const groupId = ops.findPanelGroup(dock.layout, CONTROL_PANEL_ID);
    if (groupId === null) return;
    const collapsed = dock.layout.groups[groupId]?.collapsed ?? false;
    if (collapsed !== bodyVisible) return;
    dock.toggleCollapsed(groupId);
  }, [bodyVisible, dock]);

  // What a double-click on the handle restores: the CONFIGURED placement, not
  // a fixed corner -- a viewer of an app that starts docked left is sent home
  // to docked left. Unlike the placement effect above, nothing here is
  // guarded: reset is an explicit gesture, and detach-and-redock (or
  // float-and-remake, which also drops any height the user dragged so the
  // window auto-sizes again) IS "send it home", wherever the panel had got to
  // -- floating and moved, stacked into another window, or docked elsewhere.
  React.useEffect(() => {
    resetLayoutRef.current = () =>
      dock.api.apply((layout) => {
        const groupId = ops.findPanelGroup(layout, CONTROL_PANEL_ID);
        if (groupId === null) return layout;
        if (controlLayout === "left" || controlLayout === "right") {
          const next = ops.dockToEdge(layout, [groupId], controlLayout);
          // Home is a size as well as a place: unlike the seed, reset puts a
          // resized region back to the panel's width.
          return ops.setRegionWidth(next, controlLayout, CONTROL_WIDTH_PX);
        }
        const { x, y, width } = defaultRect();
        return ops.floatGroup(layout, groupId, x, y, width).layout;
      });
  }, [dock.api, defaultRect, resetLayoutRef, controlLayout]);

  // Where is the control panel now?
  const controlGroupId = ops.findPanelGroup(dock.layout, CONTROL_PANEL_ID);
  const location =
    controlGroupId === null
      ? null
      : ops.findGroupLocation(dock.layout, controlGroupId);
  const side: "left" | "right" | "none" =
    location?.kind === "docked" ? location.edge : "none";
  const expanded =
    controlGroupId === null || dock.groups[controlGroupId]?.collapsed !== true;
  // RENDERED width (expanded px + strip/divider chrome): the notifications
  // offset must clear everything the region actually draws, not just the
  // expanded columns' model width.
  const dockedWidth =
    location?.kind === "docked"
      ? metrics.reservedWidth[location.edge]
      : CONTROL_WIDTH_PX;

  // Report dock state up to App (notifications offset).
  React.useEffect(() => {
    onDockStateChange?.({
      side: side === "none" ? null : side,
      widthPx: dockedWidth,
      expanded,
    });
  }, [side, dockedWidth, expanded, onDockStateChange]);

  return <span ref={markerRef} style={{ display: "none" }} />;
}
